# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - MAINTAINERS.md
      - LICENSE
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/.github/.github/workflows/go-ci.yml@go-ci-v1
    secrets: inherit
